alpine-lts:
  stage: test
  image: "node:lts-alpine"
  script:
    - npm ci
    - npm run test

debian-lts:
  stage: test
  image: "node:lts-buster"
  script:
    - npm ci
    - npm run test

debian-10:
  stage: test
  image: "node:10-buster"
  script:
    - npm ci
    - npm run test

debian-13:
  stage: test
  image: "node:13-buster"
  script:
    - npm ci
    - npm run test

pages:
  image: node:lts-alpine
  script:
    - npm ci
    - npm run doc:build
  artifacts:
    paths:
      - docs
