alpine-test:
  stage: test
  image: "node:lts-alpine"
  script:
    - docker version
    - npm ci
    - npm run test

alpine-debian:
  stage: test
  image: "node:lts-buster"
  script:
    - docker version
    - npm ci
    - npm run test

alpine-10:
  stage: test
  image: "node:10-buster"
  script:
    - docker version
    - npm ci
    - npm run test
